# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Duelliobuaf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Duelliobuaf
pod 'SnapKit'
pod "SwiftyStoreKit"
pod 'Alamofire'
pod "IQKeyboardManager"

end
